@startuml Inventory System - Context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
skinparam defaultFontName "D-DIN"
skinparam backgroundColor #EEEEEE

LAYOUT_TOP_DOWN()
HIDE_STEREOTYPE()

title Context diagram for Inventory Management System
right footer Version 0.1

Person(admin, "Inventory Administrator", "Creates a new inventory, disables an inventory.")
System(inventory_system, "Inventory Managenemt System", "Allows customers to keep track of their inventories.", $sprite="img:http://plantuml.com/logo3.png")
System_Ext(inventory_client, "<&cog> Component that uses inventory", "Adds items to or removes items from an inventory.", $sprite="robot")

Rel(admin, inventory_system, "Uses")
Rel(inventory_client, inventory_system, "Uses")

@enduml
